export const channels = {
  getApiKeyStatus: 'settings:get-api-key-status',
  getSettings: 'settings:get-settings',
  saveSettings: 'settings:save-settings',
  fetchModels: 'settings:fetch-models',
  saveApiKey: 'settings:save-api-key',
  clearApiKey: 'settings:clear-api-key',
  pickJobFile: 'files:pick-job-file',
  pickResumeFiles: 'files:pick-resume-files',
  pickResumeFolder: 'files:pick-resume-folder',
  resumeImportProgress: 'files:resume-import-progress',
  cancelResumeImport: 'files:cancel-resume-import',
  clearResumeImportCache: 'files:clear-resume-import-cache',
  loadCachedResumes: 'files:load-cached-resumes',
  listJobs: 'jobs:list',
  saveJob: 'jobs:save',
  deleteJob: 'jobs:delete',
  generateJobConfig: 'agents:generate-job-config',
  runScreening: 'agents:run-screening',
  screeningProgress: 'agents:screening-progress',
  runMultiAgentScreening: 'agents:run-multi-agent-screening',
  cancelScreening: 'agents:cancel-screening',
  agentStatus: 'agents:agent-status',
  exportCsv: 'export:csv',
  exportXlsx: 'export:xlsx',
} as const
